import React, {Component} from 'react';
import { StyleSheet,Dimensions } from 'react-native';

const {width,height} = Dimensions.get('window');

const styles = StyleSheet.create({
	launchSkip:{
		position:'absolute',
		top:10,
		right:10,
		fontSize:10,
		color:'white',
		paddingLeft:10,
		paddingRight:10,
		backgroundColor:'#6A59C0',
		borderRadius:5
	},
	container:{
		flex:1,
		backgroundColor:'white'
	},
	headImgSty:{
		width:90,
		height:90,
		borderRadius:45,
		marginTop:40,
		marginBottom:20,
		alignSelf:'center'
	},
	textViewSty:{
		flexDirection:'row',
		borderBottomWidth:1,
		borderColor:'#cfcfcf',
		paddingBottom:-200
	},
	inpSty:{
		width:300,
		top:10
	},
	inpTextSty:{
		color:'black',
		marginTop:13,
		paddingTop:10
	},
	forgetPwdSty:{
		color:'#77428d',
		fontSize:12,
		alignSelf:'flex-end',
		marginRight:10,
		marginTop:10,
		marginBottom:30
	},
	loginBtnSty:{
		marginBottom:10
	},
	thirdViewSty:{
		marginTop:50
	},
	thirdSpan:{
		color:'#cfcfcf',
		fontSize:10,
		alignSelf:'center',
		marginBottom:10
	},
	thirdSty:{
		flex:1,
		flexDirection:'row',
		justifyContent:'space-around'
	},
	thirdImgSty:{
		width:40,
		height:40
	},
	marginLR:{
		marginRight:10,
		marginLeft:10
	},


	icon: {
	    width: 22,
	    height: 22
	},
	coverGirl:{
		height:300
	},
	coverMsg:{
		color:'white',
		fontSize:16,
		marginTop:10,
		marginRight:10,
		alignSelf:'flex-end'
	},
	coverTime:{
		color:'white',
		fontSize:20,
		marginTop:60,
		marginLeft:10
	},
	coverName:{
		color:'white',
		fontSize:40,
		marginTop:30,
		marginLeft:10
	},
	rowSty:{
	    flex: 1,
	    flexDirection: 'row',
	    justifyContent: 'flex-start',
	},
	rowHeight:{
		height:80,
	},
	imgSty:{
	    width:50,
	    height:50,
	    borderRadius:25,
	    marginTop:15,
	    marginLeft:10
	},
	userName:{
		color:'black',
		marginLeft:10,
		marginTop:10,
		fontSize:16
	},
	userArea:{
		color:'black',
		marginLeft:10,
		marginTop:5,
		fontSize:10
	},
	userDesc:{
		color:'black',
		marginLeft:10,
		marginTop:5,
		fontSize:10
	},
	itemSeparator:{
		height:1,
		marginLeft:10,
		marginRight:10,
		backgroundColor:'rgba(100,53,201,0.1)'
	},

	coverFs:{
		height:250
	},
	fsMore:{
		flexDirection:'row',
		justifyContent:'space-between',
		paddingTop:5,
		paddingBottom:5,
		paddingLeft:10,
		paddingRight:10, 
		backgroundColor:'#eee'
	},
	fsMoreT1:{
		color:'black'
	},
	fsMoreT2:{
		color:'#77428d'
	},
	fsLists:{
		flexDirection:'row',
		justifyContent:'space-between',
		paddingTop:10,
		paddingBottom:15,
		paddingLeft:10,
		paddingRight:10
	},
	itemImg:{
		width:85,
		height:85
	},
	fsListText:{
		fontSize:12,
		color:'#222',
		marginTop:5,
		alignSelf:'center'
	},

	search:{
		height:30,
		backgroundColor:'white',
		borderRadius:5,
		padding:0,
		margin:10,
		textAlign:'center'
	},
	arrowIcon:{
		width:10,
		height:20,
		alignSelf:'flex-end',
		position:'absolute',
		right:10,
		top:13
	},
	manageItem:{
		position:'relative',
		backgroundColor:'white',
		flexDirection:'row',
		borderTopWidth:1,
		borderBottomWidth:1,
		borderColor:'#ccc',
		padding:10
	},
	manageItemText:{
		fontSize:18,
		color:'#222',
		paddingLeft: 5
	},
	logout:{
		alignSelf:'center',
		fontSize:20,
		color:'#ccc',
		marginTop:100
	},

	imgfire:{
		width:20,
		height:20
	},

	rankDimg:{
		width:30,
		height:26,
		marginLeft:10,
		marginTop:30
	},
	rankDcircle:{
		width:30,
		height:30,
		marginLeft:10,
		marginTop:28
	},
	rankDsort:{
		color:'white',
		textAlign:'center',
		marginTop:6
	},
	rankDcharmNumber:{
		flexDirection:'row',
		position:'absolute',
		top:10,
		right:10
	},

	header:{
		position:'relative',
		flexDirection:'row',
		height:40
	},
	backArrow:{
		width:14,
		height:14,
		marginTop:13,
		marginLeft:10
	},
	goback:{
		fontWeight:'bold',
		color:'white',
		marginTop:11,
	},
	uerMsgIcon:{
		width:22,
		height:16,
		position:'absolute',
		right:10,
		top:13
	},
	headertitle:{
		fontWeight:'bold',
		color:'white',
		alignSelf:'center',
		marginLeft:120
	},
	lsAvatar:{
		width:80,
		height:80,
		borderRadius:40
	},
	lsName:{
		marginLeft:10,
		marginTop:10,
		fontSize:20,
		color:'white'
	},
	lsAgeAndArea:{
		marginLeft:10,
		color:'black',
		fontSize:16
	},
	lsDesc:{
		marginTop:5,
		marginLeft:20,
		color:'black',
		fontSize:16
	},
	lsAlbumLists:{
		flexDirection:'row',
		justifyContent:'space-around',
		paddingLeft:10,
		paddingRight:10,
		paddingTop:20,
		paddingBottom:20
	},
	lsAlbumBox:{
		borderWidth:1,
		borderColor:'#77428d',
		backgroundColor:'#77428d'
	},
	lsAlbum:{
		width:80,
		height:80
	},
	lsAlbumTitle:{
		alignSelf:'center',
		fontSize:10,
		color:'white'
	},
	lsLabelLists:{
		flexDirection:'row',
		justifyContent:'space-around',
		flexWrap:'wrap'
	},
	lsLabel:{
		paddingTop:5,
		paddingBottom:5,
		paddingLeft:10,
		paddingRight:10,
		borderRadius:20,
		borderWidth:1,
		borderColor:'#77428d',
		color:'#77428d',
		marginTop:20
	},
	lsBtnList:{
		flexDirection:'row',
		justifyContent:'space-around',
		position:'absolute',
		bottom:0
	},
	lsBtn:{
		width:width / 3,
		height:48,
		backgroundColor:'#77428d',
		color:'white',
		fontSize:20,
		textAlign:'center',
		paddingTop:10
	},

	citySectionHeader:{
		color:'white',
		fontWeight:'bold',
		backgroundColor:'#6ec4f8',
		paddingLeft:10,
		paddingRight:10,
		paddingTop:5,
		paddingBottom:5
	},
	cityItem:{
		color:'black',
		padding:10
	},

	conversationHeader:{
		height:40,
		flexDirection:'row',
		justifyContent:'space-around',
		backgroundColor:'#77428d'
	},
	chatList:{
		justifyContent:'flex-end',
		paddingLeft:10,
		paddingRight:10
	},
	chatItemText:{
		backgroundColor:'#eee',
		color:'black',
		marginTop:25,
		marginBottom:10,
		padding:10,
		borderTopLeftRadius:10,
		borderBottomRightRadius:10,
		borderBottomLeftRadius:10,
		maxWidth:300
	},
	chatAvatar:{
		width:40,
		height:40,
		borderRadius:20,
		marginTop:5,
		marginLeft:5
	},
	send:{
		flexDirection:'row',
		width:width,
		height:48,
		paddingLeft:10,
		paddingRight:10,
		backgroundColor:'#eeeeee',
		position:'absolute',
		bottom:0
	},
	sendInput:{
		flexDirection:'row',
		height:40,
		marginTop:4,
		borderWidth:1,
		borderRadius:2,
		borderColor:'#77428d'
	},
	sendEmoji:{
		width:30,
		height:30,
		marginTop:5,
		marginLeft:3,
		marginRight:3
	},
	sendAlbum:{
		width:30,
		height:30,
		marginTop:10,
		marginLeft:5,
		marginRight:5
	},
	sendBtn:{
		width:width / 5.125,
		height:40,
		color:'white',
		backgroundColor:'#77428d',
		borderRadius:3,
		textAlign:'center',
		marginTop:5,
		lineHeight:30
	}


})
export default styles;